# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ccdh terminology service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: git lfs
      run: |
        git lfs pull --include=crdc-nodes/PDC-Public/documentation/prod/json/*.json
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv-to-requirements
        pipenv_to_requirements
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create .env file
      run: |
        echo -en "NEO4J_USERNAME=neo4j\nNEO4J_PASSWORD=ccdh\nNEO4J_HOST=localhost\nNEO4J_BOLT_PORT=7687\nCCDHMODEL_BRANCH=improvement-batch" > .env
    - name: Test with pytest
      run: |
        pytest
