# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: git lfs
      run: |
        git lfs pull --include=crdc-nodes/PDC-Public/documentation/prod/json/*.json
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Note: "setuptools<=57.5.0": There is/was an issue where with newer versions (was using 58.0 by default), some packages would fail: "  error in tabletext setup command: use_2to3 is invalid." We can remove this setuptools installation step in the future once setuptools has fixed this issue. - joeflack4 2021/11/11
        pip install "setuptools<=57.5.0"
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo -en "NEO4J_USERNAME=neo4j\nNEO4J_PASSWORD=ccdh\nNEO4J_HOST=localhost\nNEO4J_BOLT_PORT=7687\nREDIS_URL=redis://ccdh-redis:6379\nDOCKER_USER_TOKEN_LIMITED=notARealToken\nCCDHMODEL_BRANCH=main" > .env
    - name: Test with pytest
      run: |
        pytest
