name: Re-build and re-deploy on production and trigger CCDH model refresh

on:
  workflow_dispatch:

jobs:
  rebuild_redeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run script on server
      # shell: bash  # Usage: this ensures that env variable usage syntax is correct; Disabled because: causes yaml file syntax error
      uses: appleboy/ssh-action@master  # https://github.com/appleboy/ssh-action
      with:
        host: terminology.ccdh.io
        username: docker
        password: ${{ secrets.DOCKER_USER_PASSWORD }}
        # key: ${{ secrets.KEY }}  # not needed
        # port: ${{ secrets.PORT }}  # default: 22
        # TODO: Include 'git checkout master'? Or allow other branches?
        # TODO: Is 'exit' necessary? I'm not 100% sure, but the last time I ran the action, it seemed to stay running indefinitely.
        # timeout: 30s  # timeout - timeout for ssh to remote host, default is 30s
        command_timeout: 60m  # command_timeout - timeout for ssh command, default is 10m
        script: |
          # Step 1/3: Stop service
          cd /opt/Projects/ccdh-terminology-service
          docker-compose down

          # Step 2/3: Update codebase
          # git checkout master
          git pull

          # Step 3/3: Deploy
          cd docker
          # TODO: just need to build the API service
          docker-compose build ccdh-api
          docker-compose up
          docker exec -it ccdh-api /bin/bash
          python -m ccdh.importers.importer
          exit