name: Re-build and re-deploy on production and trigger CCDH model refresh

on:
  workflow_dispatch:

jobs:
  rebuild_redeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run script on server
      # shell: bash  # Usage: this ensures that env variable usage syntax is correct; Disabled because: causes yaml file syntax error
      uses: appleboy/ssh-action@master  # https://github.com/appleboy/ssh-action
      env:
        DOCKER_USER_TOKEN_LIMITED: ${{ secrets.DOCKER_USER_TOKEN_LIMITED }}
        DOCKER_USER_PASSWORD: ${{ secrets.DOCKER_USER_PASSWORD }}
      with:
        host: terminology.ccdh.io
        username: docker
        password: ${{ secrets.DOCKER_USER_PASSWORD }}
        # key: ${{ secrets.KEY }}  # not needed
        # port: ${{ secrets.PORT }}  # default: 22
        # TODO: Change curl script repo from "joeflack4" to "cancerDHC"
        envs: DOCKER_USER_TOKEN_LIMITED,DOCKER_USER_PASSWORD
        # timeout: 30s  # timeout - timeout for ssh to remote host, default is 30s
        command_timeout: 60m  # command_timeout - timeout for ssh command, default is 10m
        script: |
          # Step 1/4: Stop service
          cd /opt/Projects/ccdh-terminology-service
          docker-compose down

          # Step 2/4: Update codebase
          git pull
          # Is this necessary? Maybe just because I hadn't set SSH key up w/ GitHub was the issue:
          # echo "$DOCKER_USER_PASSWORD" | sudo -S git pull

          # Step 3/4: Deploy
          cd docker
          # TODO: just need to build the API service
          docker-compose build ccdh-api
          docker-compose up
          docker exec -it ccdh-api /bin/bash
          python -m ccdh.importers.importer

          # Step 4/4: Trigger refresh of CCDH model
          # https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer '$DOCKER_USER_TOKEN_LIMITED'" \
            https://api.github.com/repos/joeflack4/ccdhmodel/dispatches \
            -d '{"event_type":"Re-build and re-deploy (repository_dispatch from ccdh-terminology-service)"}'